apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: doc-publish-disadvantage
  title: Illustration Of 'publish' Disadvantage
  description: The purpose of this template is to emphasize flaws of 'publish' action.
  tags:
    - illustration
    - publish
    - disadvantage

spec:
  type: service
  owner: employee.ldap@homedepot.com

  parameters:
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        repoUrl: ${{ parameters.repoUrl }}

